WatchShopV3/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WatchShopV3.Models;
using WatchShopV3.Repositories;

namespace WatchShopV3.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IBrandRepository _brandRepository;
        private readonly IStyleRepository _styleRepository;
        public ProductController(IProductRepository productRepository,
        ICategoryRepository categoryRepository, IBrandRepository brandRepository, IStyleRepository styleRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            _brandRepository = brandRepository;
            _styleRepository = styleRepository;
        }
        // Hiển thị danh sách sản phẩm
        public async Task<IActionResult> Display(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

		public async Task<IActionResult> Index(string searchString)
		{
			var products = _productRepository.GetAll();

			if (!String.IsNullOrEmpty(searchString))
			{
				products = products.Where(s => s.Name.Contains(searchString));
			}

			return View(await products.ToListAsync());
		}
	}
}

WatchShopV3/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WatchShopV3.Data;
using WatchShopV3.Extensions;
using WatchShopV3.Models;
using WatchShopV3.Repositories;

public class ShoppingCartController : Controller
{
	private readonly IProductRepository _productRepository;
	private readonly ApplicationDbContext _context;
	private readonly UserManager<ApplicationUser> _userManager;
	public ShoppingCartController(ApplicationDbContext context,
	UserManager<ApplicationUser> userManager, IProductRepository
	productRepository)
	{
		_productRepository = productRepository;
		_context = context;
		_userManager = userManager;
	}
	
    public async Task<IActionResult> AddToCart(int productId, int quantity)
    {
        // Giả sử bạn có phương thức lấy thông tin sản phẩm từ productId
        var product = await GetProductFromDatabase(productId);
        var cartItem = new CartItem
        {
            ProductId = productId,
            Name = product.Name,
            Price = product.Price,
            Quantity = quantity
        };
        var cart =
        HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new
        ShoppingCart();
        cart.AddItem(cartItem);
        HttpContext.Session.SetObjectAsJson("Cart", cart);
        return RedirectToAction("Index");
    }
    public IActionResult Index()
    {
        var cart =
        HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new
        ShoppingCart();
        return View(cart);
    }
    // Các actions khác...
    private async Task<Product> GetProductFromDatabase(int productId)
    {
        // Truy vấn cơ sở dữ liệu để lấy thông tin sản phẩm
        var product = await _productRepository.GetByIdAsync(productId);
        return product;
    }
    public IActionResult RemoveFromCart(int productId)
    {
        var cart =
        HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
        if (cart is not null)
        {
            cart.RemoveItem(productId);
            // Lưu lại giỏ hàng vào Session sau khi đã xóa mục
            HttpContext.Session.SetObjectAsJson("Cart", cart);
        }
        return RedirectToAction("Index");
    }

	public IActionResult Checkout()
	{
		return View(new Order());
	}
	[HttpPost]
	public async Task<IActionResult> Checkout(Order order)
	{
		var cart =
		HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
		if (cart == null || !cart.Items.Any())
		{
			// Xử lý giỏ hàng trống...
			return RedirectToAction("Index");
		}
		var user = await _userManager.GetUserAsync(User);
		order.UserId = user.Id;
		order.OrderDate = DateTime.UtcNow;
		order.TotalPrice = cart.Items.Sum(i => i.Price * i.Quantity);
		order.OrderDetails = cart.Items.Select(i => new OrderDetail
		{
			ProductId = i.ProductId,
			Quantity = i.Quantity,
			Price = i.Price
		}).ToList();
		_context.Orders.Add(order);
		await _context.SaveChangesAsync();
		HttpContext.Session.Remove("Cart");
		return View("OrderCompleted", order); // Trang xác nhận hoànthành đơn hàng
    }

}

WatchShopV3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WatchShopV3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WatchShopV3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">WatchShopV3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WatchShopV3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WatchShopV3/Views/Shared/_LayoutForBuyProduct.cshtml
<!DOCTYPE html>
<html lang="zxx">

<head>
	<meta charset="UTF-8">
	<meta name="description" content="Ogani Template">
	<meta name="keywords" content="Ogani, unica, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Ogani | Template</title>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

	<!-- Css Styles -->
	<link rel="stylesheet" href="~/WatchShopSource/css/bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="~/WatchShopSource/css/font-awesome.min.css" type="text/css">
	<link rel="stylesheet" href="~/WatchShopSource/css/elegant-icons.css" type="text/css">
	<link rel="stylesheet" href="~/WatchShopSource/css/nice-select.css" type="text/css">
	<link rel="stylesheet" href="~/WatchShopSource/css/jquery-ui.min.css" type="text/css">
	<link rel="stylesheet" href="~/WatchShopSource/css/owl.carousel.min.css" type="text/css">
	<link rel="stylesheet" href="~/WatchShopSource/css/slicknav.min.css" type="text/css">
	<link rel="stylesheet" href="~/WatchShopSource/css/style.css" type="text/css">


</head>

<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	
	<!-- Header Section Begin -->
	<header class="header">
		<div class="header__top">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 col-md-6">
						<div class="header__top__left">
							<ul>
								<li><i class="fa fa-envelope"></i>Thời gian luôn quý giá - Đồng hồ của bạn nên cũng vậy.</li>
								<li>Welcome to Watch Store</li>
							</ul>
						</div>
					</div>
					<div class="col-lg-6 col-md-6">
						<div class="header__top__right">
							<div class="header__top__right__social">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-linkedin"></i></a>
								<a href="#"><i class="fa fa-pinterest-p"></i></a>
								<a asp-area="Admin" asp-controller="ProductManager" asp-action="Index"><i class="fa fa-tachometer" style="margin-right: 6px"></i> Admin Dashboard</a>
							</div>

							<div class="header__top__right__auth">
								<partial name="_LoginPartial" />
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container" style="margin-top: 80px; margin-bottom: 200px">
			@RenderBody()
		</div>
	</header>
	<!-- Header Section End -->
	<!-- Featured Section Begin -->
	

	<!-- Featured Section End -->
	<!-- Footer Section Begin -->
	<footer class="footer spad">
		<div class="container">

			<div class="row">
				<div class="col-lg-12">
					<div class="footer__about text-center">
						<ul>
							<li>Address: 60-49 Road 11378 New York</li>
							<li>Phone: +65 11.188.888</li>
							<li>Email: hello@colorlib.com</li>
						</ul>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-12">
					<div class="footer__copyright">
						<div class="footer__copyright__text">
							<p>
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</p>
						</div>
						<div class="footer__copyright__payment"><img src="~/WatchShopSource/img/payment-item.png" alt=""></div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- Footer Section End -->
	<!-- Js Plugins -->
	<script src="~/WatchShopSource/js/jquery-3.3.1.min.js"></script>
	<script src="~/WatchShopSource/js/bootstrap.min.js"></script>
	<script src="~/WatchShopSource/js/jquery.nice-select.min.js"></script>
	<script src="~/WatchShopSource/js/jquery-ui.min.js"></script>
	<script src="~/WatchShopSource/js/jquery.slicknav.js"></script>
	<script src="~/WatchShopSource/js/mixitup.min.js"></script>
	<script src="~/WatchShopSource/js/owl.carousel.min.js"></script>
	<script src="~/WatchShopSource/js/main.js"></script>
	@await RenderSectionAsync("Scripts", required: false)


</body>

</html>

WatchShopV3/Views/Shared/_LayoutWatchShop.cshtml
<!DOCTYPE html>
<html lang="zxx">

<head>
	<meta charset="UTF-8">
	<meta name="description" content="Ogani Template">
	<meta name="keywords" content="Ogani, unica, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Ogani | Template</title>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

	<!-- Css Styles -->
	<link rel="stylesheet" href="~/WatchShopSource/css/bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="~/WatchShopSource/css/font-awesome.min.css" type="text/css">
	<link rel="stylesheet" href="~/WatchShopSource/css/elegant-icons.css" type="text/css">
	<link rel="stylesheet" href="~/WatchShopSource/css/nice-select.css" type="text/css">
	<link rel="stylesheet" href="~/WatchShopSource/css/jquery-ui.min.css" type="text/css">
	<link rel="stylesheet" href="~/WatchShopSource/css/owl.carousel.min.css" type="text/css">
	<link rel="stylesheet" href="~/WatchShopSource/css/slicknav.min.css" type="text/css">
	<link rel="stylesheet" href="~/WatchShopSource/css/style.css" type="text/css">


</head>

<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Humberger Begin -->
	<div class="humberger__menu__overlay"></div>
	<div class="humberger__menu__wrapper">
		<div class="humberger__menu__logo">
			<a href="#"><img src="~/WatchShopSource/img/logo.png" alt=""></a>
		</div>
		<div class="humberger__menu__cart">
			<ul>
				<li><a href="#"><i class="fa fa-heart"></i> <span>1</span></a></li>
				<li><a href="#"><i class="fa fa-shopping-bag"></i> <span>3</span></a></li>
			</ul>
			<div class="header__cart__price">item: <span>$150.00</span></div>
		</div>
		<div class="humberger__menu__widget">
			<div class="header__top__right__language">
				<img src="~/WatchShopSource/img/language.png" alt="">
				<div>English</div>
				<span class="arrow_carrot-down"></span>
				<ul>
					<li><a href="#">Spanis</a></li>
					<li><a href="#">English</a></li>
				</ul>
			</div>
			<div class="header__top__right__auth">
				<a href="#"><i class="fa fa-user"></i> Login</a>
			</div>
		</div>
		<nav class="humberger__menu__nav mobile-menu">
			<ul>
				<li class="active"><a href="./index.html">Home</a></li>
				<li><a href="./shop-grid.html">Shop</a></li>
				<li>
					<a href="#">Pages</a>
					<ul class="header__menu__dropdown">
						<li><a href="./shop-details.html">Shop Details</a></li>
						<li><a href="./shoping-cart.html">Shoping Cart</a></li>
						<li><a href="./checkout.html">Check Out</a></li>
						<li><a href="./blog-details.html">Blog Details</a></li>
					</ul>
				</li>
				<li><a href="./blog.html">Blog</a></li>
				<li><a href="./contact.html">Contact</a></li>
			</ul>
		</nav>
		<div id="mobile-menu-wrap"></div>
		<div class="header__top__right__social">
			<a href="#"><i class="fa fa-facebook"></i></a>
			<a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-linkedin"></i></a>
			<a href="#"><i class="fa fa-pinterest-p"></i></a>
		</div>
		<div class="humberger__menu__contact">
			<ul>
				<li><i class="fa fa-envelope"></i> hello@colorlib.com</li>
				<li>Free Shipping for all Order of $99</li>
			</ul>
		</div>
	</div>
	<!-- Humberger End -->
	<!-- Header Section Begin -->
	<header class="header">
		<div class="header__top">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 col-md-6">
						<div class="header__top__left">
							<ul>
								<li>Thời gian luôn quý giá - Đồng hồ của bạn cũng nên vậy.</li>
								<li>Welcome to Watch Store</li>
							</ul>
						</div>
					</div>
					<div class="col-lg-6 col-md-6">
						<div class="header__top__right">
							<div class="header__top__right__social">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-linkedin"></i></a>
								<a href="#"><i class="fa fa-pinterest-p"></i></a>
								<a asp-area="Admin" asp-controller="ProductManager" asp-action="Index"><i class="fa fa-tachometer" style="margin-right: 6px"></i> Admin Dashboard</a>
							</div>

							<div class="header__top__right__auth">
								<partial name="_LoginPartial" />
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-lg-3">
					<div class="header__logo">
						<a asp-controller="Product" asp-action="Index"><img src="~/WatchShopSource/img/WatchShop.png" alt=""></a>
					</div>
				</div>
				<div class="col-lg-6">
					<nav class="header__menu">
						<ul style="display:flex; justify-content: center">
							<li class="active"><a href="./index.html">Home</a></li>
							<li><a href="./blog.html">Blog</a></li>
							<li><a href="./contact.html">Contact</a></li>
						</ul>
					</nav>
				</div>
				<div class="col-lg-3">
					<div class="header__cart">
						<ul>
							<li><a asp-controller="ShoppingCart" asp-action="Index"><i class="fa fa-shopping-bag"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="humberger__open">
				<i class="fa fa-bars"></i>
			</div>
		</div>
	</header>
	<!-- Header Section End -->
	<!-- Featured Section Begin -->
	@RenderBody()

	<!-- Featured Section End -->
	<!-- Footer Section Begin -->
	<footer class="footer spad">
		<div class="container">

			<div class="row">
				<div class="col-lg-12">
					<div class="footer__about text-center">
						<ul>
							<li>Address: Hutech E</li>
							<li>Phone: +84858047257</li>
							<li>Email: nguyenthaihoc@gmail.com</li>
						</ul>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-12">
					<div class="footer__copyright">
						<div class="footer__copyright__text">
							<p>
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</p>
						</div>
						<div class="footer__copyright__payment"><img src="~/WatchShopSource/img/payment-item.png" alt=""></div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- Footer Section End -->
	<!-- Js Plugins -->
	<script src="~/WatchShopSource/js/jquery-3.3.1.min.js"></script>
	<script src="~/WatchShopSource/js/bootstrap.min.js"></script>
	<script src="~/WatchShopSource/js/jquery.nice-select.min.js"></script>
	<script src="~/WatchShopSource/js/jquery-ui.min.js"></script>
	<script src="~/WatchShopSource/js/jquery.slicknav.js"></script>
	<script src="~/WatchShopSource/js/mixitup.min.js"></script>
	<script src="~/WatchShopSource/js/owl.carousel.min.js"></script>
	<script src="~/WatchShopSource/js/main.js"></script>
	@await RenderSectionAsync("Scripts", required: false)


</body>

</html>