WatchShopV3/Areas/Admin/Controllers/CategoryManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WatchShopV3.Models;
using WatchShopV3.Repositories;

namespace WatchShopV3.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CategoryManagerController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;

        public CategoryManagerController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        // Hiển thị danh sách sản phẩm
        public async Task<IActionResult> Index(string searchString)
        {
            var categories = _categoryRepository.GetAll();

            if (!String.IsNullOrEmpty(searchString))
            {
                categories = categories.Where(s => s.Name.Contains(searchString));
            }

            return View(await categories.ToListAsync());
        }
        // Hiển thị form thêm sản phẩm mới

        public async Task<IActionResult> Add()
        {
            return View();
        }
        // Xử lý thêm sản phẩm mới
        [HttpPost]
        public async Task<IActionResult> Add(Category category)
        {
            if (category == null)
            {
                return BadRequest("Category object is null");
            }

            if (ModelState.IsValid)
            {
                await _categoryRepository.AddAsync(category);
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }


        // Hiển thị form cập nhật sản phẩm

        public async Task<IActionResult> Update(int id)
        {
            var category = await _categoryRepository.GetByIdAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        // Xử lý cập nhật sản phẩm
        [HttpPost]
        public async Task<IActionResult> Update(int id, Category category)
        {
            if (ModelState.IsValid)
            {
                var existingCategory = await _categoryRepository.GetByIdAsync(id);
                if (existingCategory == null)
                {
                    return NotFound();
                }

                // Cập nhật các thông tin khác của danh mục
                existingCategory.Name = category.Name;
                existingCategory.Note = category.Note;

                await _categoryRepository.UpdateAsync(existingCategory);

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }


        // Hiển thị form xác nhận xóa sản phẩm
        public async Task<IActionResult> Delete(int id)
        {
            var category = await _categoryRepository.GetByIdAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // Xử lý xóa sản phẩm
        [HttpPost, ActionName("DeleteConfirmed")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _categoryRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Display(int id)
        {
            var product = await _categoryRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
    }
}

WatchShopV3/Areas/Admin/Views/CategoryManager/Add.cshtml
@model WatchShopV3.Models.Category

@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group" style="max-height: 100px; overflow-y: auto;">
                <label asp-for="Note" class="control-label"> </label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"> </span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary btn-animate" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<style>
    .btn-animate {
        transition: transform 0.2s ease-in-out; /* Sử dụng transition cho hiệu ứng mềm mại */
    }

        .btn-animate:hover {
            transform: scale(1.1); /* Phóng to nút lên 110% khi di chuột qua */
        }

   
</style>

WatchShopV3/Areas/Admin/Views/CategoryManager/Delete.cshtml
@model WatchShopV3.Models.Category

<h2>Delete Category</h2>

<form asp-action="DeleteConfirmed" method="post">
    <input type="hidden" asp-for="Id" />
    <p>Are you sure you want to delete @Model.Name?</p>
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

WatchShopV3/Areas/Admin/Views/CategoryManager/Display.cshtml
@model WatchShopV3.Models.Category

@{
    ViewData["Title"] = "Display";
}

<h1>Display</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Update" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WatchShopV3/Areas/Admin/Views/CategoryManager/Index.cshtml
@model IEnumerable<WatchShopV3.Models.Category>

@{
    ViewData["Title"] = "Index";
}

<h2 style="text-align:center">Category Manager</h2>

<form asp-controller="CategoryManager" asp-action="Index">
    <p>
        Title: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<p>
    <a asp-action="Add">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="note-column">
                @Html.DisplayNameFor(model => model.Note)
            </th>

            <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Note)
            </td>
            <td>
                    <a asp-action="Update" asp-route-id="@item.Id" class="update-link">Edit</a> |
                    <a asp-action="Display" asp-route-id="@item.Id" class="details-link">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="delete-link">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

<style>
    .update-link,
    .details-link,
    .delete-link {
        padding: 5px 10px; /* Thêm khoảng cách xung quanh văn bản */
        border-radius: 4px; /* Làm cho các liên kết trở nên bo tròn */
        transition: background-color 0.2s, color 0.2s; /* Thêm hiệu ứng chuyển động */
    }

    .update-link {
        color: #28a745; /* Màu xanh lá cây cho Edit */
        border: 1px solid #28a745; /* Viền xanh lá cây cho Edit */
    }

    .details-link {
        color: #007bff; /* Màu xanh dương cho Details */
        border: 1px solid #007bff; /* Viền xanh dương cho Details */
    }

    .delete-link {
        color: #dc3545; /* Màu đỏ cho Delete */
        border: 1px solid #dc3545; /* Viền đỏ cho Delete */
    }

        /* Hiệu ứng hover */
        .update-link:hover,
        .details-link:hover,
        .delete-link:hover {
            text-decoration: underline; /* Gạch chân khi di chuột qua */
            background-color: #f8f9fa; /* Màu nền khi di chuột qua */
            font-weight: bold; /* Tô màu đậm khi di chuột qua */
        }
    .note-column {
        max-width: 200px; /* Đặt kích thước tối đa cho cột */
        overflow: hidden; /* Ẩn nội dung tràn ra ngoài */
        text-overflow: ellipsis; /* Hiển thị dấu chấm (...) khi nội dung tràn ra ngoài */
        white-space: nowrap; /* Ngăn cách các từ xuống dòng mới */
    }

</style>

WatchShopV3/Areas/Admin/Views/CategoryManager/Update.cshtml
@model WatchShopV3.Models.Category

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}