WatchShopV3/Areas/Admin/Controllers/StyleManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WatchShopV3.Models;
using WatchShopV3.Repositories;

namespace WatchShopV3.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class StyleManagerController : Controller
    {
        
		private readonly IStyleRepository _styleRepository;

		public StyleManagerController(IStyleRepository styleRepository)
		{
			_styleRepository = styleRepository;
		}

        // Hiển thị danh sách sản phẩm

        public async Task<IActionResult> Index(string searchString)
        {
            var products = _styleRepository.GetAll();

            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(s => s.Name.Contains(searchString));
            }

            return View(await products.ToListAsync());
        }
        // Hiển thị form thêm sản phẩm mới

        public async Task<IActionResult> Add()
		{
			return View();
		}
		// Xử lý thêm sản phẩm mới

		[HttpPost]
		public async Task<IActionResult> Add(Style style)
		{
			if (style == null)
			{
				return BadRequest("Category object is null");
			}

			if (ModelState.IsValid)
			{
				await _styleRepository.AddAsync(style);
				return RedirectToAction(nameof(Index));
			}
			return View(style);
		}


		// Hiển thị thông tin chi tiết sản phẩm

		public async Task<IActionResult> Display(int id)
		{
			var style = await _styleRepository.GetByIdAsync(id);
			if (style == null)
			{
				return NotFound();
			}
			return View(style);
		}
		// Hiển thị form cập nhật sản phẩm

		public async Task<IActionResult> Update(int id)
		{
			var style = await _styleRepository.GetByIdAsync(id);
			if (style == null)
			{
				return NotFound();
			}

			return View(style);
		}
		// Xử lý cập nhật sản phẩm
		[HttpPost]
		public async Task<IActionResult> Update(int id, Style style)
		{
			if (ModelState.IsValid)
			{
				var existingStyle = await _styleRepository.GetByIdAsync(id);
				if (existingStyle == null)
				{
					return NotFound();
				}

				// Cập nhật các thông tin khác của danh mục
				existingStyle.Name = style.Name;
				existingStyle.Description = style.Description;

                await _styleRepository.UpdateAsync(existingStyle);

				return RedirectToAction(nameof(Index));
			}
			return View(style);
		}


		// Hiển thị form xác nhận xóa sản phẩm
		public async Task<IActionResult> Delete(int id)
		{
			var style = await _styleRepository.GetByIdAsync(id);
			if (style == null)
			{
				return NotFound();
			}
			return View(style);
		}

		// Xử lý xóa sản phẩm
		[HttpPost, ActionName("DeleteConfirmed")]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			await _styleRepository.DeleteAsync(id);
			return RedirectToAction(nameof(Index));
		}

    }
}

WatchShopV3/Areas/Admin/Views/StyleManager/Add.cshtml
@model WatchShopV3.Models.Style

@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<h4>Style</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary btn-animate" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="back-to-list-link">Back to List</a>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<style>
    .btn-animate {
        transition: transform 0.2s ease-in-out; /* Sử dụng transition cho hiệu ứng mềm mại */
    }

        .btn-animate:hover {
            transform: scale(1.1); /* Phóng to nút lên 110% khi di chuột qua */
        }

    .back-to-list-link {
        text-decoration: none;
        padding: 5px 10px; /* Thêm khoảng cách xung quanh văn bản */
        border: 1px solid #007bff; /* Thêm viền màu xanh dương cho liên kết */
        border-radius: 4px; /* Làm cho viền trở nên bo tròn */
        color: #007bff; /* Màu xanh dương cho văn bản */
        transition: color 0.2s, background-color 0.2s, border-color 0.2s; /* Thêm hiệu ứng mềm mại */
        margin-top: 100px; /* Lùi liên kết xuống dưới 10px */
    }


        .back-to-list-link:hover {
            color: #0056b3; /* Màu xanh dương đậm khi di chuột qua */
            background-color: #f8f9fa; /* Màu nền xám nhạt khi di chuột qua */
            border-color: #0056b3; /* Màu viền xanh dương đậm khi di chuột qua */
        }

</style>

WatchShopV3/Areas/Admin/Views/StyleManager/Delete.cshtml
@model WatchShopV3.Models.Style

<h2>Delete Style</h2>

<form asp-action="DeleteConfirmed" method="post">
    <input type="hidden" asp-for="Id" />
    <p>Are you sure you want to delete @Model.Name?</p>
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

WatchShopV3/Areas/Admin/Views/StyleManager/Display.cshtml
@model WatchShopV3.Models.Style

@{
    ViewData["Title"] = "Display";
}

<h1>Display</h1>

<div>
    <h4>Style</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Update" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WatchShopV3/Areas/Admin/Views/StyleManager/Index.cshtml
@model IEnumerable<WatchShopV3.Models.Style>

@{
    ViewData["Title"] = "Index";
}

<h2 style="text-align: center">Style Manager</h2>

<form asp-controller="StyleManager" asp-action="Index">
    <p>
        Title: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<p>
    <a asp-action="Add">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                    <a asp-action="Update" asp-route-id="@item.Id" class="edit-link">Edit</a> |
                    <a asp-action="Display" asp-route-id="@item.Id" class="details-link">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="delete-link">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

<style>
    .edit-link,
    .details-link,
    .delete-link {
        padding: 5px 10px; /* Thêm khoảng cách xung quanh văn bản */
        border-radius: 4px; /* Làm cho các liên kết trở nên bo tròn */
        transition: background-color 0.2s, color 0.2s; /* Thêm hiệu ứng chuyển động */
    }

    .edit-link {
        color: #28a745; /* Màu xanh lá cây cho Edit */
        border: 1px solid #28a745; /* Viền xanh lá cây cho Edit */
    }

    .details-link {
        color: #007bff; /* Màu xanh dương cho Details */
        border: 1px solid #007bff; /* Viền xanh dương cho Details */
    }

    .delete-link {
        color: #dc3545; /* Màu đỏ cho Delete */
        border: 1px solid #dc3545; /* Viền đỏ cho Delete */
    }

        /* Hiệu ứng hover */
        .edit-link:hover,
        .details-link:hover,
        .delete-link:hover {
            text-decoration: underline; /* Gạch chân khi di chuột qua */
            background-color: #f8f9fa; /* Màu nền khi di chuột qua */
            font-weight: bold; /* Tô màu đậm khi di chuột qua */
        }

</style>

WatchShopV3/Areas/Admin/Views/StyleManager/Update.cshtml
@model WatchShopV3.Models.Style

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Style</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}